select 
	strftime('%m', billing.[date]) || '/' || strftime('%d', billing.[date]) || '/' || strftime('%Y',billing.[date]) as [Date],
	employee as [Employee],
	proj.projectfilename || ' | ' || billing.projectname as [Project],
	payitem.workdescription as [Activity],
	billing.detail as [Description],
	billing.quantity as [Hours],
	'0' as [Cost Rate],
	round(billing.projectbillingrate,2) as [Bill Rate],
	'TRUE' as [Billable],
	'Un Billed' as [Billed Status],
	round(billing.projectbillingrate*billing.quantity,2) as [Amount],
	'Un-submitted' as [Submit Status],
	'' as [Approved By],
	'FALSE' as [Overtime],
	'FALSE' as [Extra],
	'FALSE' as [Paid],
	"12:00:00 AM" as [Start Time],
	"12:00:00 AM" as [Stop Time],
	'' as [Income Account],
	'' as [Expense Account],
	'' as [Class],
	'' as [Classification],
	'0' as [Tax1 %],
	'0' as [Tax2 %],
	'0' as [Tax3 %],
	'' as [Purchase Tax Rate],
	'0' as [WUD %],
	'' as [Vendor Bill Number],
	'' as [Company Invoice Number],
	'FALSE' as [IsDraft],
	client.client as [Client],
	'0' as [Attachments],
	'' as [Created By],
	strftime('%m','now') || '/' || strftime('%d','now') || '/' || strftime('%Y','now') as [Created On],
	'' as [Created By],
	strftime('%m','now') || '/' || strftime('%d','now') || '/' || strftime('%Y','now') as [Last Updated]
from tblClientBilling billing
left join tblPayItem payitem on payitem.payitemid = billing.payitemid
left join tblProject proj on proj.projectid = billing.projectid
left join tblClient client on proj.clientid = client.clientid
order by billing.[date], billing.employee asc;