

SELECT DISTINCT workdescription
FROM tblPayItem
WHERE workdescription COLLATE NOCASE IN (
    'Additional GPS Receiver- No Base Station',
    'ATV',
    'ATV (Daily Rate)',
    'CAD Engineer, E.I.T',
    'CAD Engineer, E.I.T. to P.E.',
    'CAD ENGINEER, EIT-PE W/ 4 YRS EXPERIENCE',
    'CAD engineer, EIT-PE with 4 yrs exp',
    'CAD operator,courthouse research, constr insp',
    'Cad Operator/Courthouse Research',
    'CAD OPERATOR/COURTHOUSE RESEARCH/CONST. INSP',
    'Cad Operator/Courthouse Research/Construction Insp',
    'Cad operator/courthouse research/construction insp',
    'CADD / Survey Technician',
    'CADD Engineer',
    'COMPANY VEHICLE',
    'Company Vehicle (Daily Rate)',
    'Construction Engineer',
    'Construction Inspection',
    'DATA COLLECION DEVICE',
    'Drafter',
    'Engineer Senior',
    'Environmental Inspector',
    'EQP1- company vehicle',
    'EQP2- ATV (4wheeler, gator, etc)',
    'EQP3- GPS base rover unit',
    'EQP5- Total station & data collector',
    'FAA approved UAV Pilot and MicroDrones M3000DL',
    'FAA approved UAV Pilot and UAV with LIDAR Payload',
    'Field Tech Incidental',
    'Field Technichian Incidental',
    'field technician incidental',
    'GPS- 1 MAN CREW',
    'GPS BASE ROVER SYSTEM',
    'Inspector I',
    'Laborer',
    'MILEAGE',
    'MISC- loddging, meals, reimbursable expenses',
    'Miscellaneous',
    'MISCELLANEOUS EXPENSE',
    'OH Equipment Maintenance',
    'OH Network Administation',
    'OH Office File Management',
    'OH Office Management',
    'OH Travel/ Supply Maintenance',
    'One man robotic GPS Crew',
    'OP6- Engineer II',
    'OP8-CADD operator/design technician I',
    'OP9- CADD operator/Design technician II',
    'P.E. GENERAL CONSULTING FEE',
    'Party/Crew Chief',
    'Project Engineer',
    'Project Engineer - Modeling',
    'Project engineer 5-9 years experience',
    'Project Engineer, P.E.',
    'PROJECT ENGINEER, P.E. WITH 5-9 YEARS EXPERIENCE',
    'Real Time GPS ( Trimble R10 system )',
    'Real Time GPS ( Trimble R12 system )',
    'Real Time GPS ( Trimble System )  1 Man Crew',
    'REAL TIME GPS (TRIMBLE R10) SYSTEM',
    'REAL TIME GPS- 2 MAN CREW',
    'Real time GPS(Trimble R8, R10, R12 system) 2 man c',
    'Real Time GPS-2 man ( Trimble System )',
    'Registered Professional Land Surveyor',
    'ROBOTIC TS- 1 MAN CREW',
    'Rod/Chainman',
    'SENIOR PROFESSIONAL ENGINEER',
    'Senior Professional Engineer, 10 years experience',
    'Senior professional engineer, 10 yrs exp',
    'SP2- Licensed professional land surveyor',
    'SP3- party/crew chief',
    'SP5- rodman',
    'Total station (Topcon TS w/data collector) 2 man',
    'Total Station Crew',
    'TOTAL STATION W/ DATA COLLECTION DEVICE',
    'Trimble S10 Spatial Imaging Scanner and Crew'
)
ORDER BY workdescription;