update tblPayItem set workdescription = 'Additional GPS Receiver- No Base Station:' where workdescription collate nocase = 'Additional GPS Receiver ( Trimble R8 system no Bas';
update tblPayItem set workdescription = 'ATV:' where workdescription collate nocase = 'ATV';
update tblPayItem set workdescription = 'ATV (Daily Rate):' where workdescription collate nocase = 'ATV (Daily Rate)';
update tblPayItem set workdescription = 'CAD Engineer, E.I.T:' where workdescription collate nocase = 'CAD Engineer, E.I.T';
update tblPayItem set workdescription = 'CAD Engineer, E.I.T:' where workdescription collate nocase = 'CAD Engineer, E.I.T. to P.E.';
update tblPayItem set workdescription = 'CAD Engineer, EIT-PE w/ 4 Yrs Exp:' where workdescription collate nocase = 'CAD ENGINEER, EIT-PE W/ 4 YRS EXPERIENCE';
update tblPayItem set workdescription = 'CAD Engineer, EIT-PE w/ 4 Yrs Exp:' where workdescription collate nocase = 'CAD engineer, EIT-PE with 4 yrs exp';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase = 'CAD operator,courthouse research, constr insp';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase = 'Cad Operator/Courthouse Research';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase = 'CAD OPERATOR/COURTHOUSE RESEARCH/CONST. INSP';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase = 'Cad Operator/Courthouse Research/Construction Insp';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase = 'Cad operator/courthouse research/construction insp';
update tblPayItem set workdescription = 'CAD Operator, Courthouse Research, Construction Inspection:' where workdescription collate nocase like '%cad operator%';
update tblPayItem set workdescription = 'CADD/Survey Technician:' where workdescription collate nocase = 'CADD / Survey Technician';
update tblPayItem set workdescription = 'CADD Engineer:' where workdescription collate nocase = 'CADD Engineer';
update tblPayItem set workdescription = 'Company Vehicle:' where workdescription collate nocase = 'COMPANY VEHICLE';
update tblPayItem set workdescription = 'Company Vehicle (Daily Rate):' where workdescription collate nocase = 'Company Vehicle (Daily Rate)';
update tblPayItem set workdescription = 'Construction Engineer:' where workdescription collate nocase = 'Construction Engineer';
update tblPayItem set workdescription = 'Construction Inspection:' where workdescription collate nocase = 'Construction Inspection';
update tblPayItem set workdescription = 'Data Collection Device:' where workdescription collate nocase = 'DATA COLLECION DEVICE';
update tblPayItem set workdescription = 'Drafter:' where workdescription collate nocase like '%Drafter%';
update tblPayItem set workdescription = 'Engineer Senior:' where workdescription collate nocase = 'Engineer Senior';
update tblPayItem set workdescription = 'Environmental Inspector:' where workdescription collate nocase = 'Environmental Inspector';
update tblPayItem set workdescription = 'EQP1- Company Vehicle:' where workdescription collate nocase = 'EQP1- company vehicle';
update tblPayItem set workdescription = 'EQP2 ATV (4 Wheeler, Gator, etc.):' where workdescription collate nocase = 'EQP2- ATV (4wheeler, gator, etc)';
update tblPayItem set workdescription = 'EQP3 GPS Base & Rover Unit:' where workdescription collate nocase = 'EQP3- GPS base rover unit';
update tblPayItem set workdescription = 'EQP5 Total Station & Data Collector:' where workdescription collate nocase = 'EQP5- Total station & data collector';
update tblPayItem set workdescription = 'FAA Approved UAV Pilot and MicroDrones M3000DL:' where workdescription collate nocase = 'FAA approved UAV Pilot and MicroDrones M3000DL';
update tblPayItem set workdescription = 'FAA Approved UAV Pilot and MicroDrones M3000DL:' where workdescription collate nocase = 'FAA approved UAV Pilot and MicroDrones M3000DL Dro';
update tblPayItem set workdescription = 'FAA Approved UAV Pilot and UAV w/ LIDAR Payload:' where workdescription collate nocase = 'FAA approved UAV Pilot and UAV with LIDAR Payload';
update tblPayItem set workdescription = 'Field Technichian Incidental:' where workdescription collate nocase = 'Field Tech Incidental';
update tblPayItem set workdescription = 'Field Technichian Incidental:' where workdescription collate nocase = 'Field Technichian Incidental';
update tblPayItem set workdescription = 'Field Technichian Incidental:' where workdescription collate nocase like '%field technician incidental%';
update tblPayItem set workdescription = 'GPS- 1 Man Crew:' where workdescription collate nocase = 'GPS- 1 MAN CREW';
update tblPayItem set workdescription = 'GPS Base Rover System:' where workdescription collate nocase = 'GPS BASE ROVER SYSTEM';
update tblPayItem set workdescription = 'Inspector I:' where workdescription collate nocase = 'Inspector I';
update tblPayItem set workdescription = 'Laborer:' where workdescription collate nocase = 'Laborer';
update tblPayItem set workdescription = 'Mileage:' where workdescription collate nocase like '%mileage%';
update tblPayItem set workdescription = 'Misc-lodging,meals, reimbursable expenses:' where workdescription collate nocase = 'MISC- loddging, meals, reimbursable expenses';
update tblPayItem set workdescription = 'Miscellaneous:' where workdescription collate nocase = 'Miscellaneous';
update tblPayItem set workdescription = 'Miscellaneous:' where workdescription collate nocase = 'MISCELLANEOUS EXPENSE';
update tblPayItem set workdescription = 'Misc-lodging,meals, reimbursable expenses:' where workdescription collate nocase = 'Misc-lodging,meals, reimbursable expenses';
update tblPayItem set workdescription = 'Overhead:' where workdescription collate nocase = 'OH Equipment Maintenance';
update tblPayItem set workdescription = 'Overhead:' where workdescription collate nocase = 'OH Network Administation';
update tblPayItem set workdescription = 'Overhead:' where workdescription collate nocase = 'OH Office File Management';
update tblPayItem set workdescription = 'Overhead:' where workdescription collate nocase = 'OH Office Management';
update tblPayItem set workdescription = 'Overhead:' where workdescription collate nocase = 'OH Travel/ Supply Maintenance';
update tblPayItem set workdescription = 'One-Man Robotic GPS Crew:' where workdescription collate nocase = 'One man robotic GPS Crew';
update tblPayItem set workdescription = 'OP6 Engineer II:' where workdescription collate nocase = 'OP6- Engineer II';
update tblPayItem set workdescription = 'OP8 CADD Operator/Design Technician I:' where workdescription collate nocase = 'OP8-CADD operator/design technician I';
update tblPayItem set workdescription = 'OP9 CADD Operator/Design Technician II:' where workdescription collate nocase = 'OP9- CADD operator/Design technician II';
update tblPayItem set workdescription = 'Senior Professional Engineer:' where workdescription collate nocase = 'P.E. GENERAL CONSULTING FEE';
update tblPayItem set workdescription = 'Party/Crew Chief:' where workdescription collate nocase = 'Party/Crew Chief';
update tblPayItem set workdescription = 'Project Engineer:' where workdescription collate nocase = 'Project Engineer';
update tblPayItem set workdescription = 'Project Engineer - Modeling:' where workdescription collate nocase = 'Project Engineer - Modeling';
update tblPayItem set workdescription = 'Project Engineer - PE w/ 5-9 Yrs Exp:' where workdescription collate nocase like '%Project engineer 5-9 years experience%';
update tblPayItem set workdescription = 'Project Engineer:' where workdescription collate nocase = 'Project Engineer, P.E.';
update tblPayItem set workdescription = 'Project Engineer - PE w/ 5-9 Yrs Exp:' where workdescription collate nocase like '%PROJECT ENGINEER, P.E. WITH 5-9 YEARS EXPERIENCE%';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'Real Time GPS ( Trimble R10 system )';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'Real Time GPS ( Trimble R12 system )';
update tblPayItem set workdescription = 'Real Time GPS (Trimble System) 1 Man Crew:' where workdescription collate nocase = 'Real Time GPS ( Trimble System )  1 Man Crew';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'REAL TIME GPS (TRIMBLE R10) SYSTEM';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'REAL TIME GPS- 2 MAN CREW';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'Real time GPS(Trimble R8, R10, R12 system) 2 man c';
update tblPayItem set workdescription = 'Real Time GPS-2 Man (Trimble System):' where workdescription collate nocase = 'Real Time GPS-2 man ( Trimble System )';
update tblPayItem set workdescription = 'Registered Professional Land Surveyor:' where workdescription collate nocase = 'Registered Professional Land Surveyor';
update tblPayItem set workdescription = 'Robotic TS - One Man Crew:' where workdescription collate nocase = 'ROBOTIC TS- 1 MAN CREW';
update tblPayItem set workdescription = 'Rod/Chainman:' where workdescription collate nocase = 'Rod/Chainman';
update tblPayItem set workdescription = 'Senior Professional Engineer:' where workdescription collate nocase = 'Senior Professional Engineer';
update tblPayItem set workdescription = 'Senior Professional Engineer:' where workdescription collate nocase = 'SENIOR PROFESSIONAL ENGINEER';
update tblPayItem set workdescription = 'Senior Professional Engineer w/ 10 Yrs Exp:' where workdescription collate nocase like '%Senior Professional Engineer, 10 years experience%';
update tblPayItem set workdescription = 'Senior Professional Engineer w/ 10 Yrs Exp:' where workdescription collate nocase like '%Senior professional engineer, 10 yrs exp%';
update tblPayItem set workdescription = 'SP2 Licensed Professional Surveyor:' where workdescription collate nocase = 'SP2- Licensed professional land surveyor';
update tblPayItem set workdescription = 'SP3 Party/Crew Chief:' where workdescription collate nocase = 'SP3- party/crew chief';
update tblPayItem set workdescription = 'SP5 Rodman:' where workdescription collate nocase = 'SP5- rodman';
update tblPayItem set workdescription = 'Total Station (Topcon TS w/ Data Collector) 2 Man:' where workdescription collate nocase = 'Total station (Topcon TS w/data collector) 2 man';
update tblPayItem set workdescription = 'Total Station Crew:' where workdescription collate nocase = 'Total Station Crew';
update tblPayItem set workdescription = 'Total Station w/ Data Collection Device:' where workdescription collate nocase = 'TOTAL STATION W/ DATA COLLECTION DEVICE';
update tblPayItem set workdescription = 'Trimble S10 Spatial Imaging Scanner and Crew:' where workdescription collate nocase = 'Trimble S10 Spatial Imaging Scanner and Crew';
