update tblProject set projectname = '12010 | WAYNESBURG SIDEWALK PROJECT' where projectname = 'WAYNESBURG SIDEWALK PROJECT';
update tblProject set projectname = '17263 | PLANNING & ZONING' where projectname = 'PLANNING & ZONING';
update tblProject set projectname = '18193 | JAMESTOWN- CREATE NEW TRACT' where projectname = 'JAMESTOWN- CREATE NEW TRACT';
update tblProject set projectname = '18295 | IMPROVEMENTS PROJECT' where projectname = 'IMPROVEMENTS PROJECT';
update tblProject set projectname = '19228 | GARNER PROPERTY KY HWY 80' where projectname = 'GARNER PROPERTY KY HWY 80';
update tblProject set projectname = '20418 | BANCROFT - NITRO 69KV REBUILD -- GROUND SURVEY' where projectname = 'BANCROFT - NITRO 69KV REBUILD -- GROUND SURVEY';
update tblProject set projectname = '21162 | BANCROFT-NITRO 69 KV ROW' where projectname = 'BANCROFT-NITRO 69 KV ROW';
update tblProject set projectname = '21164G | LESLIE- STINNET' where projectname = 'LESLIE- STINNET';
update tblProject set projectname = '21194B | MIDKIFF - STONE BRANCH - GROUND SURVEY' where projectname = 'MIDKIFF - STONE BRANCH - GROUND SURVEY';
update tblProject set projectname = '21225 | MCKINNEY WATER DISTRICT' where projectname = 'MCKINNEY WATER DISTRICT';
update tblProject set projectname = '21284 | LINCOLN CO SANITATION DISTRICT SEWER-PHASE 3' where projectname = 'LINCOLN CO SANITATION DISTRICT SEWER-PHASE 3';
update tblProject set projectname = '21420AG | GARRETT - EASTERN - TLE Ground Survey & Staking' where projectname = 'GARRETT - EASTERN - TLE Ground Survey & Staking';
update tblProject set projectname = '21420BG | GARRETT - SOFTSHELL; TLE GROUND SURVEY' where projectname = 'GARRETT - SOFTSHELL; TLE GROUND SURVEY';
update tblProject set projectname = '22095 | 815 HWY 461 BOUNDARY SURVEY' where projectname = '815 HWY 461 BOUNDARY SURVEY';
update tblProject set projectname = '22236G3 | ORINOCO-STONE-GROUND SURVEY' where projectname = 'ORINOCO-STONE-GROUND SURVEY';
update tblProject set projectname = '22333 | PDI APPLICATION' where projectname = 'PDI APPLICATION';
update tblProject set projectname = '22438 | JOSH MORGAN & WILLIAMSBURG VILLAGE DRAINAGE' where projectname = 'JOSH MORGAN & WILLIAMSBURG VILLAGE DRAINAGE';
update tblProject set projectname = '22459 | NEWFOUNDLAND-CONSTRUCTION STAKING' where projectname = 'NEWFOUNDLAND-CONSTRUCTION STAKING';
update tblProject set projectname = '22467 | WYOMING STATION - Zach Bowman' where projectname = 'WYOMING STATION - Zach Bowman';
update tblProject set projectname = '23025 | NEW OFFICES-SOMERSET KY' where projectname = 'NEW OFFICES-SOMERSET KY';
update tblProject set projectname = '23086 | RETRACE 100 ACRES- Y HWY 501' where projectname = 'RETRACE 100 ACRES- Y HWY 501';
update tblProject set projectname = '23090 | 130 ACRES/ SUBDIVISION DESIGN' where projectname = '130 ACRES/ SUBDIVISION DESIGN';
update tblProject set projectname = '23107 | KY HWY 1547' where projectname = 'KY HWY 1547';
update tblProject set projectname = '23217 | ELIZABETHTOWN #1 DISTRIBUTION STATION' where projectname = 'ELIZABETHTOWN #1 DISTRIBUTION STATION';
update tblProject set projectname = '23225 | GABRIEL PROJECT' where projectname = 'GABRIEL PROJECT';
update tblProject set projectname = '23297B | RATLIFF STATION-TOPOGRAPHIC SURVEY' where projectname like '%RATLIFF STATION-TOPOGRAPHIC%';
update tblProject set projectname = '23297C | RATLIFF STATION | DAVID & VICI CONLEY' where projectfilename = '23297C';
update tblProject set projectname = '23334 | BULLITT CO PIPELINE STAKING AND SURVEY' where projectname = 'BULLITT CO PIPELINE STAKING AND SURVEY- STEVE BEAT';
update tblProject set projectname = '23346 | UK HOSPITAL-UNDERGROUND TRANSMISSION CORRIDOR' where projectname = 'UK HOSPITAL-UNDERGROUND TRANSMISSION CORRIDOR';
update tblProject set projectname = '23354 | SHELBY GREEN SECTION 3 PHASE 2' where projectname = 'SHELBY GREEN SECTION 3 PHASE 2';
update tblProject set projectname = '23361C | MERCERS BOTTOM EXTENSION' where projectname = 'MERCERS BOTTOM EXTENSION';
update tblProject set projectname = '23375 | LYNCH - POCKET | 99 YEAR LEASE - EASEMENT DRAWING' where projectname like '%LYNCH - POCKET%';
update tblProject set projectname = '23438 | RUSSELL CO BUS GARAGE' where projectname = 'RUSSELL CO BUS GARAGE';
update tblProject set projectname = '23463 | HAZARD-JACKSON TOPO SURVEY AND STRUCTURE STAKING' where projectname = 'HAZARD-JACKSON TOPO SURVEY AND STRUCTURE STAKING';
update tblProject set projectname = '23479 | AUTUMN LEAF STATION' where projectname = 'AUTUMN LEAF STATION';
update tblProject set projectname = '23518 | Subdivision Junction City' where projectname = 'Subdivision Junction City';
update tblProject set projectname = '23520 | OLDHAM RESERVE' where projectname = 'OLDHAM RESERVE';
update tblProject set projectname = '24057 | HEADQUARTER-MURPHYSVILLE CONSTRUCTION STAKING' where projectname = 'HEADQUARTER-MURPHYSVILLE CONSTRUCTION STAKING';
update tblProject set projectname = '24071B | TRACT # 2 DIVISION' where projectname = 'TRACT # 2 DIVISION';
update tblProject set projectname = '24095 | LESLIE- WOOTEN SWPPP INSPECTIONS' where projectname = 'LESLIE- WOOTEN SWPPP INSPECTIONS';
update tblProject set projectname = '24098 | LESLIE- STINNET- SWPPP INSPECTIONS WO 81294780' where projectname = 'LESLIE- STINNET- SWPPP INSPECTIONS WO 81294780';
update tblProject set projectname = '24101 | ZAXBY''S' where projectname = 'ZAXBY''S';
update tblProject set projectname = '24123B | HENRY CLAY STATION TOPOGRAPHIC SURVEY' where projectname = 'HENRY CLAY STATION TOPOGRAPHIC SURVEY';
update tblProject set projectname = '24146 | BIG HILL TAP' where projectname = 'BIG HILL TAP';
update tblProject set projectname = '24151A | DISMAL RIV-GRUNDY-LOONY GROUND SURVEY' where projectname = 'DISMAL RIV-GRUNDY-LOONY GROUND SURVEY';
update tblProject set projectname = '24157 | ATHLETIC FIELD HOUSES' where projectname = 'ATHLETIC FIELD HOUSES';
update tblProject set projectname = '24168 | SUBDIVISION IN MADISON CO' where projectname = 'SUBDIVISION IN MADISON CO';
update tblProject set projectname = '24188 | CABIN CREEK-LONDON; GROUND SURVEY' where projectname = 'CABIN CREEK-LONDON; GROUND SURVEY';
update tblProject set projectname = '24206A | Levisa Station Layout and Verification Work' where projectname = 'Levisa Station Layout and Verification Work';
update tblProject set projectname = '24206G | LEVISA 69KV EXTENSION GROUND SURVEY' where projectname = 'LEVISA 69KV EXTENSION GROUND SURVEY';
update tblProject set projectname = '24206RW | LEVISA 69KV EXTENSION T LINE ROW' where projectname = 'LEVISA 69KV EXTENSION T LINE ROW';
update tblProject set projectname = '24237 | HORSE SOLDIER' where projectname = 'HORSE SOLDIER';
update tblProject set projectname = '24269 | MARION & METTS TRANSMISSION LINE' where projectname = 'MARION & METTS TRANSMISSION LINE';
update tblProject set projectname = '24302A | Boundary Survey for (3) Lots in Industrial Park #2' where projectname = 'Boundary Survey for (3) Lots in Industrial Park #2';
update tblProject set projectname = '24317 | COBURG STATION 69 KV-NEW BREAKER STATION' where projectname = 'COBURG STATION 69 KV-NEW BREAKER STATION';
update tblProject set projectname = '24335 | SUBDIVISION IN CLINTON CO' where projectname = 'SUBDIVISION IN CLINTON CO';
update tblProject set projectname = '24338 | JOHN DEERE-DANVILLE KY' where projectname = 'JOHN DEERE-DANVILLE KY';
update tblProject set projectname = '24352 | RETRACE LOT IN SOMERSET ON MONTICELLO RD' where projectname = 'RETRACE LOT IN SOMERSET ON MONTICELLO RD';
update tblProject set projectname = '24362 | BONNIEVILLE-STEPHENSBURG CONSTRUCTION STAKING' where projectname = 'BONNIEVILLE-STEPHENSBURG CONSTRUCTION STAKING';
update tblProject set projectname = '24372 | 295 ACRES' where projectname = '295 ACRES';
update tblProject set projectname = '24402 | I-75' where projectname = 'I-75, EXIT 97- MADISON COUNTY';
update tblProject set projectname = '24406 | BONNIEVILLE - CUB RUN | PO TR12234' where projectname like '%CUB RUN%';
update tblProject set projectname = '24406A | BONNIEVILLE-CLUB RUN' where projectname = 'BONNIEVILLE-CLUB RUN';
update tblProject set projectname = '24443 | 139984 |MIDDLETOWN-MID VALLEY-CONSTRUCTION STAKING' where projectname like '%MIDDLETOWN-MID VALLEY-CONSTRUCTION STAKING%';
update tblProject set projectname = '24478 | COUNTRY CLUB-DECO ARCHITECTS' where projectname = 'COUNTRY CLUB-DECO ARCHITECTS';
update tblProject set projectname = '24495BG | HENRY CLAY-DORTON-GROUND SURVEY' where projectname = 'HENRY CLAY-DORTON-GROUND SURVEY';
update tblProject set projectname = '24495BRW | HENRY CLAY - DORTON |  ROW' where projectname like '%HENRY CLAY - DORTON%';
update tblProject set projectname = '24495DG | HENRY CLAY-BREAKS-GROUND SURVEY' where projectname = 'HENRY CLAY-BREAKS-GROUND SURVEY';
update tblProject set projectname = '24495DRW | Henry Clay - Breaks | ROW' where projectfilename = '24495DRW';
update tblProject set projectname = '24497 | C-STORE SITE' where projectname = 'C-STORE SITE';
update tblProject set projectname = '25008 | COOPER STATION | CERTIFICATION SURVEY' where projectname LIKE '%COOPER STATION%';
update tblProject set projectname = '25044 | CR-MIDDLESBORO-HARROGATE | Cumberland Gap' where projectname like '%CR-MIDDLESBORO-HARROGATE%';
update tblProject set projectname = '25048 | TEXAS ROADHOUSE IN DANVILLE' where projectname = 'TEXAS ROADHOUSE IN DANVILLE';
update tblProject set projectname = '25057 | BETSY LANE- SOUTH PIKEVILLE' where projectname = 'BETSY LANE- SOUTH PIKEVILLE';
update tblProject set projectname = '25066ARW | PRESTONSBURG - KENWOOD | ROW PROJECT' where projectname like '%PRESTONSBURG - KENWOOD%';
update tblProject set projectname = '25066BRW | THELMA - KENWOOD | ROW PROJECT' where projectname LIKE '%THELMA - KENWOOD%';
update tblProject set projectname = '25067 | PEG HILL - AREA D - PHASE 3 (SPURLOCK LF)' where projectname = 'PEG HILL - AREA D - PHASE 3 (SPURLOCK LF)';
update tblProject set projectname = '25082 | MULDRAUGH EXISTING CONDITIONS SITE SURVEY' where projectname = 'MULDRAUGH EXISTING CONDITIONS SITE SURVEY';
update tblProject set projectname = '25086 | LI 171265-GRESHAM-SMITH RELOCATION' where projectname = 'LI 171265-GRESHAM-SMITH RELOCATION';
update tblProject set projectname = '25090' where projectname = 'CREATE 10 ACRE TRACT';
update tblProject set projectname = '25108 | SCAN COAL BARGES AT SPURLOCK' where projectname = 'SCAN COAL BARGES AT SPURLOCK';
update tblProject set projectname = '25121 | BOUNDARY RETRACEMENT IN DANVILLE' where projectname = 'BOUNDARY RETRACEMENT IN DANVILLE';
update tblProject set projectname = '25130 | McCreary - KU WOFFORD | CONSTRUCTION STAKING' where projectname LIKE '%McCreary - KU WOFFORD%';
update tblProject set projectname = '25145 | PUBLIX ALTA SURVEY-SOMERSET' where projectname = 'PUBLIX ALTA SURVEY-SOMERSET';
update tblProject set projectname = '25168 | RUSSELL CO FIELD HOUSE AND BUS GARAGE STAKING' where projectname = 'RUSSELL CO FIELD HOUSE AND BUS GARAGE STAKING';
update tblProject set projectname = '25169D | CLINTON COUNTY HIGH SCHOOL-CIVIL DESIGN' where projectname = 'CLINTON COUNTY HIGH SCHOOL-CIVIL DESIGN';
update tblProject set projectname = '25170 | RENAKER SUBSTATION CIVIL PLANS' where projectname = 'RENAKER SUBSTATION CIVIL PLANS';
update tblProject set projectname = '25177 | LI-161858  LONDON TO SWEET HOLLOW RR PERMIT' where projectname like '%TO SWEET HOLLOW RR PERMIT%';
update tblProject set projectname = '25178 | BOWLING GREEN' where projectname = 'BOWLING GREEN';
update tblProject set projectname = '25190 | RE-PIN LOTS 6 & 7-WANDERING HILLS SUBDIVISION' where projectname = 'RE-PIN LOTS 6 & 7-WANDERING HILLS SUBDIVISION';
update tblProject set projectname = '25218 | BOYS & GIRLS CLUB-GLASGOW' where projectname = 'BOYS & GIRLS CLUB-GLASGOW';
update tblProject set projectname = '25234 | PAVILION DR KYTC PERMIT' where projectname = 'PAVILION DR KYTC PERMIT';
update tblProject set projectname = '25240 | VILLAS @ RIDGEFIELD FARM' where projectname = 'VILLAS @ RIDGEFIELD FARM';
update tblProject set projectname = '25246 | FACTORY ST RR PERMIT' where projectname = 'FACTORY ST RR PERMIT';
update tblProject set projectname = '25248 | RETRACE CAMENISCH PROPERTY' where projectname = 'RETRACE CAMENISCH PROPERTY';
update tblProject set projectname = '25252 | RETRACE 2320 CHRISMAN LANE' where projectname = 'RETRACE 2320 CHRISMAN LANE';
update tblProject set projectname = '25255 | CARPENTERS CREEK' where projectname = 'CARPENTERS CREEK';
update tblProject set projectname = '25273 | PIPELINE PROJECT ASBUILTS MILL CREEK MC-5' where projectname = 'PIPELINE PROJECT ASBUILTS MILL CREEK MC-5';
update tblProject set projectname = '25275 | MARCHING BAND PRACTICE FIELD' where projectname = 'MARCHING BAND PRACTICE FIELD';
update tblProject set projectname = '25307 | BOUNDARY SURVEY- 90 WATERFALL LANE' where projectname = 'BOUNDARY SURVEY- 90 WATERFALL LANE';
update tblProject set projectname = '25309 | PARCEL 032-00-00-010.00' where projectname = 'PARCEL 032-00-00-010.00';
update tblProject set projectname = '25310 | PARCEL 032-00-00-005.00' where projectname = 'PARCEL 032-00-00-005.00';
update tblProject set projectname = '25316 | LI-169839 | PARIS TRANSMISSION SWPPP INSPECTION' where projectname like '%PARIS TRANSMISSION%';
update tblProject set projectname = '25322 | LI-161119-PR Harlan Y - Pineville 161kV' where projectname = 'LI-161119-PR Harlan Y - Pineville 161kV';
update tblProject set projectname = '25325A | 2025 LKE FLEET SURVEYING - CCR' where projectname = '2025 LKE FLEET SURVEYING - CCR';
update tblProject set projectname = '25332 | SUMMER SHADE-BARON PROJECT ID# 14285' where projectname = 'SUMMER SHADE-BARON PROJECT ID# 14285';
update tblProject set projectname = '25333 | 43 ACRES RETRACEMENT ON HUFF ROAD' where projectname = '43 ACRES RETRACEMENT ON HUFF ROAD';
update tblProject set projectname = '25338 | MT WASHINGTON PIPELINE ASBUILTS' where projectname = 'MT WASHINGTON PIPELINE ASBUILTS';
update tblProject set projectname = '25339 | CAT RIDGE ROAD' where projectname = 'CAT RIDGE ROAD';
update tblProject set projectname = '25341 | CONSTRUCTION INSPECTION' where projectname = 'CONSTRUCTION INSPECTION';
update tblProject set projectname = '25343 | DAHLIA-HIGHLAND KYTC PERMITS' where projectname = 'DAHLIA-HIGHLAND KYTC PERMITS';
update tblProject set projectname = '25344 | RETRACE AND STAKE HOME IN OLD BRIDGE' where projectname = 'RETRACE AND STAKE HOME IN OLD BRIDGE';
update tblProject set projectname = '25346 | LI-162624 |  PR Leitchfield-Stephensburg' where projectname like '%PR Leitchfield-Stephensburg%';
update tblProject set projectname = '25349 | RETRACE THE MAY WARREN ESTATE' where projectname = 'RETRACE THE MAY WARREN ESTATE';
update tblProject set projectname = '25354 | CUT OUT 20 ACRES @ 1180 WESLEY MILLER RD' where projectname = 'CUT OUT 20 ACRES @ 1180 WESLEY MILLER RD';
update tblProject set projectname = '25357 | 1685 KY HWY 328' where projectname = '1685 KY HWY 328';
update tblProject set projectname = '25367 | K9-2024 | Bardstown-Hodgenville EKPC Str 248 ABLI' where projectfilename = '25367';
update tblProject set projectname = '25370A | Estes Farm 69kV' where projectname = 'Estes Farm 69kV';
update tblProject set projectname = '25372 | TOMMY''S CAR WASH- CULVERS' where projectname = 'TOMMY''S CAR WASH- CULVERS';
update tblProject set projectname = '25374 | COOPER STATION-TOPOGRAPHIC SURVEY' where projectfilename = '25374';
update tblProject set projectname = '25387 | RICHMOND RD FUTURE STATION' where projectname = 'RICHMOND RD FUTURE STATION';
update tblProject set projectname = '25388 | SKYLIGHT TO PENAL FARM KYTC PERMITS' where projectname = 'SKYLIGHT TO PENAL FARM KYTC PERMITS';
update tblProject set projectname = '25393 | ASTEMO PLANT SITE DESIGN' where projectname = 'ASTEMO PLANT SITE DESIGN';
update tblProject set projectname = '25399 | NEW VISTA HEALTH' where projectname = 'NEW VISTA HEALTH';
update tblProject set projectname = '25405 | CREEKSIDE SUBDIVISION-HARRODSBURG' where projectname like '%CREEKSIDE SUBDIVISION-HARRODSBURG%';
update tblProject set projectname = '25410 | RR PERMIT-HARLAN CO' where projectname like '%RR PERMIT-HARLAN CO%';
update tblProject set projectname = '25415 | KY 393 RELOCATION' where projectname like '%KY 393 RELOCATION%';
update tblProject set projectname = '25416 | 1055 CRAWFORD LANE' where projectname like '%1055 CRAWFORD LANE%';
update tblProject set projectname = '25418 | MEDICAL MARIJUANA SALES' where projectname like '%MEDICAL MARIJUANA SALES%';
update tblProject set projectname = '25422 | CREATE TRACT AROUND HOUSE' where projectname like '%CREATE TRACT AROUND HOUSE%';
update tblProject set projectname = '25424 | FERGUSON SOUTH-SOMERSET PERMITS' where projectname like '%FERGUSON SOUTH-SOMERSET PERMITS%';
update tblProject set projectname = '25427 | MADISONVILLE SERVICE CENTER' where projectfilename = '25427';
update tblProject set projectname = '25430 | LI-1711452 MSD PADDYS RUN' where projectname = 'LI-1711452 MSD PADDYS RUN';
update tblProject set projectname = '25432 | LOUDON AVE-PARIS' where projectname = 'LOUDON AVE-PARIS';
update tblProject set projectname = '25434 | SHELBY GREEN PHASE 3 CONSTRUCTION LAYOUT' where projectname = 'SHELBY GREEN PHASE 3 CONSTRUCTION LAYOUT';
update tblProject set projectname = '25435A | (Scott Co) - PENN-RENAKER CONSTRUCTION STAKING' where projectname = '(Scott Co) - PENN-RENAKER CONSTRUCTION STAKING';
update tblProject set projectname = '25440 | COMMERCIAL PROPERTY ON US HWY 68' where projectname = 'COMMERCIAL PROPERTY ON US HWY 68';
update tblProject set projectname = '25448 | PROJECT#13967-AM POWELL-ZACHARIAH' where projectname = 'PROJECT#13967-AM POWELL-ZACHARIAH';
update tblProject set projectname = '25449 | DAJCOR ALUMINUM' where projectname = 'DAJCOR ALUMINUM';
update tblProject set projectname = '25450 | CREATE 2 TRACTS ON REMAINING PROPERTY' where projectname = 'CREATE 2 TRACTS ON REMAINING PROPERTY';
update tblProject set projectname = '25451 | BUYING PROPERTY FROM MIKE MCKENNA' where projectname = 'BUYING PROPERTY FROM MIKE MCKENNA';
update tblProject set projectname = '25452 | EDA PROPERTY CIVIL DESIGN' where projectname = 'EDA PROPERTY CIVIL DESIGN';
update tblProject set projectname = '25461 | SPURLOCK - FIRE CONVERSION SURVEY' where projectname = 'SPURLOCK - FIRE CONVERSION SURVEY';
update tblProject set projectname = '25463 | DIVIDE FARM ON ELKINS-ROGERS RD INTO TRACTS' where projectname = 'DIVIDE FARM ON ELKINS-ROGERS RD INTO TRACTS';
update tblProject set projectname = '25465 | STAKE HOUSE ON CLAUNCH RD' where projectname = 'STAKE HOUSE ON CLAUNCH RD';
update tblProject set projectname = '25468 | ALTA SURVEY-CULVERS' where projectname = 'ALTA SURVEY-CULVERS';
update tblProject set projectname = '25469 | DIVIDE 40 ACRES ON RUBE BROWN ROAD' where projectname = 'DIVIDE 40 ACRES ON RUBE BROWN ROAD';
update tblProject set projectname = '25470 | CUT OUT 10 ACRES-MCCORMICKS CHURCH RD' where projectname = 'CUT OUT 10 ACRES-MCCORMICKS CHURCH RD';
update tblProject set projectname = '25471 | Interstate Crossing Surveys' where projectname = 'Interstate Crossing Surveys';
update tblProject set projectname = '25473 | COOPER - ALCALDE | Boundary Tie Surveys' where projectname like '%COOPER - ALCALDE%';
update tblProject set projectname = '25478 | FINCHVILLE CAP ALIGNMENT' where projectname = 'FINCHVILLE CAP ALIGNMENT';
update tblProject set projectname = '25480 | LI-160526 PR-MORGANFIELD-LIVINGSTON COUNTY' where projectname = 'LI-160526 PR-MORGANFIELD-LIVINGSTON COUNTY';
update tblProject set projectname = '25482 | ALBANY-SNOW-CONSTRUCTION STAKING' where projectname = 'ALBANY-SNOW-CONSTRUCTION STAKING';
update tblProject set projectname = '25483 | CYNTHIANA-RENACKER' where projectname = 'CYNTHIANA-RENACKER';
update tblProject set projectname = '25486 | EXISTING CONDITIONS & DRIVEWAY DESIGN' where projectname = 'EXISTING CONDITIONS & DRIVEWAY DESIGN';
update tblProject set projectname = '25488 | CUT OUT 10 ACRES ON SCHUMER RD' where projectname = 'CUT OUT 10 ACRES ON SCHUMER RD';
update tblProject set projectname = '25489 | UK HOSPITAL UNDERGROUND PHASE 2' where projectname = 'UK HOSPITAL UNDERGROUND PHASE 2';
update tblProject set projectname = '25490 | CUT OUT 5 ACRES ON MITCHELSBURG RD' where projectname = 'CUT OUT 5 ACRES ON MITCHELSBURG RD';
update tblProject set projectname = '25491 | CUT OUT 2 ACRES ON WEBSTER RD' where projectname = 'CUT OUT 2 ACRES ON WEBSTER RD';
update tblProject set projectname = '25492 | EKY PIPELINE EXISTING CONDITIONS CORRIDOR SURVEY' where projectname = 'EKY PIPELINE EXISTING CONDITIONS CORRIDOR SURVEY';
update tblProject set projectname = '25494 | LI-174853-S PR-ARNOLD-DELVINTA' where projectname = 'LI-174853-S PR-ARNOLD-DELVINTA';
update tblProject set projectname = '25498 | WARNER FERTILIZER RR PERMIT' where projectname = 'WARNER FERTILIZER RR PERMIT';
update tblProject set projectname = '25499 | LI-170252 PR DELVINTA-LAKE REBA' where projectname = 'LI-170252 PR DELVINTA-LAKE REBA';
update tblProject set projectname = '25500 | LI-170366 FOUNDATION STAKING' where projectname = 'LI-170366 FOUNDATION STAKING';
update tblProject set projectname = '25501 | LI-176739 MUD LANE-SOUTH PARK' where projectname = 'LI-176739 MUD LANE-SOUTH PARK';
update tblProject set projectname = '25502 | 383 LANE DRIVE' where projectname = '383 LANE DRIVE';
update tblProject set projectname = '25503 | LI-170721 ALGONQUIN-STEWART CIRCUIT #695008' where projectname = 'LI-170721 ALGONQUIN-STEWART CIRCUIT #695008';
update tblProject set projectname = '25504 | LI-177425 TEP-MOT-RIVER GREEN-TEXAS' where projectname = 'LI-177425 TEP-MOT-RIVER GREEN-TEXAS';
update tblProject set projectname = '25505 | Bluegrass Plains Solar -CONSTRUCTION LAYOUT' where projectname = 'Bluegrass Plains Solar -CONSTRUCTION LAYOUT';
update tblProject set projectname = '25506 | ZAXBY''S IN CORBIN' where projectname = 'ZAXBY''S IN CORBIN';
update tblProject set projectname = '25507 | DANVILLE MANOR ALTA SURVEY' where projectname = 'DANVILLE MANOR ALTA SURVEY';
update tblProject set projectname = '25509 | MONITORING WELLS SURVEY @ GREEN RIVER' where projectname = 'MONITORING WELLS SURVEY @ GREEN RIVER';
update tblProject set projectname = '25510 | HIGBY MILL-UK MED CENTER PERMITS' where projectname = 'HIGBY MILL-UK MED CENTER PERMITS';
update tblProject set projectname = '25511 | CUT OUT 15 ACRES ON MITCHELL LANE' where projectname = 'CUT OUT 15 ACRES ON MITCHELL LANE';
update tblProject set projectname = '25512 | FLEMING-FREMONT STAKING STRUCTURES' where projectname = 'FLEMING-FREMONT STAKING STRUCTURES';
update tblProject set projectname = '25513 | LI-176603 Wofford - Farley | Str Staking' where projectfilename = '25513';
update tblProject set projectname = '25514AG | Allen – Prestonsburg 46kv Line' where projectname like '%Prestonsburg 46kv Line%';
update tblProject set projectname = '25514BG | Betsy Layne – Allen 138kV Line' where projectname like '%Allen 138kV Line%';
update tblProject set projectname = '25514CG | Allen - East Prestonsburg 46kV Line' where projectfilename like '%25514CG%';
update tblProject set projectname = '25514DG | McKinney – Allen 46kV Line' where projectfilename like '%25514DG%';
update tblProject set projectname = '25515 | HENDRICKSON ADDITION' where projectname = 'HENDRICKSON ADDITION';
update tblProject set projectname = '25519 | Northern Bobwhite Solar Field' where projectname = 'Northern Bobwhite Solar Field';
update tblProject set projectname = '25520 | RETRACE 70 ACRES ON 510 YATES RD' where projectname = 'RETRACE 70 ACRES ON 510 YATES RD';
update tblProject set projectname = '25521 | GROUND TRUTH SURVEYS-15 SITES' where projectname = 'GROUND TRUTH SURVEYS-15 SITES';
update tblProject set projectname = '25522 | RETRACE AND DIVIDE MCKINNEY BAPTIST CHURCH PROPERT' where projectname = 'RETRACE AND DIVIDE MCKINNEY BAPTIST CHURCH PROPERT';
update tblProject set projectname = '25523 | Bellefonte Substation | Construction Layout' where projectfilename = '25523';
update tblProject set projectname = '25525 | FIVE STAR IN MONTICELLO' where projectname = 'FIVE STAR IN MONTICELLO';
update tblProject set projectname = '25526 | ROCKCASTLE CO SCHOOLS-SPORTS COMPLEX' where projectname = 'ROCKCASTLE CO SCHOOLS-SPORTS COMPLEX';
update tblProject set projectname = '25531 | BLUEGRASS-HURSTBOURNE-RESEARCH' where projectname = 'BLUEGRASS-HURSTBOURNE-RESEARCH';
update tblProject set projectname = '25532 | LI-1774430-TEP-MOT-DIXON-NEBO' where projectname = 'LI-1774430-TEP-MOT-DIXON-NEBO';
update tblProject set projectname = '25533 | BISHOP-ETHEL' where projectname = 'BISHOP-ETHEL';
update tblProject set projectname = '25534 | RETRACE LOT 2-PLAT CAB-702' where projectname = 'RETRACE LOT 2-PLAT CAB-702';
update tblProject set projectname = '26001 | PULASKI STONE' where projectname = 'PULASKI STONE';
update tblProject set projectname = '26002 | LAKE CUMBERLAND STONE' where projectname = 'LAKE CUMBERLAND STONE';
update tblProject set projectname = '26005 | PROPERTY LINE INVESTIGATION' where projectname = 'PROPERTY LINE INVESTIGATION';
update tblProject set projectname = '26006 | ADDITION TO CASTLE ROCK SUBDIVISION' where projectname = 'ADDITION TO CASTLE ROCK SUBDIVISION';
update tblProject set projectname = '26007 | LI 176603 CRT WOFFORD-FARLEY' where projectname = 'LI 176603 CRT WOFFORD-FARLEY';
update tblProject set projectname = '26008A | LI-164326 ESR MANCHESTER SOUTH-EASEMENT BOUNDARY T' where projectname = 'LI-164326 ESR MANCHESTER SOUTH-EASEMENT BOUNDARY T';
update tblProject set projectname = '26009 | KINGSPORT MALL-EASEMENT SURVEY' where projectname = 'KINGSPORT MALL-EASEMENT SURVEY';
update tblProject set projectname = '26010 | STAKE HOUSE-LOT 28 ON LOVERS LANE' where projectname = 'STAKE HOUSE-LOT 28 ON LOVERS LANE';
update tblProject set projectname = '33333 | OH Equipment Maintenance' where projectname = 'OH Equipment Maintenance';
update tblProject set projectname = '55555 | OH Office Management' where projectname = 'OH Office Management';
update tblProject set projectname = '66666 | OH- Project Management' where projectname = 'OH- Project Management';
